### PR TITLE
Save all figures as SVG

### PR DESCRIPTION
**Pull request by asinghvi17**
Improves resolution and text

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
Thanks!

**Comment by ChrisRackauckas** [comment]
Can we somehow automatically do this to all?

**Comment by asinghvi17** [comment]
I dont see why not...you just locate the end of the header and insert this text before it

**Comment by ChrisRackauckas** [comment]
yeah, but I think we can template these somehow?

**Comment by asinghvi17** [comment]
We can also pass this option to the call to `weave`.  I don't think I can run the examples locally though.

**Pull request merged**
