### PR TITLE
Use plot_chain for turing_inference

### PR DESCRIPTION
**Pull request by Vaibhavdixit02**

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
Reduce the noise on Fitz?

**Comment by Vaibhavdixit02** [comment]
I thought I had pushed the changes, apparently I hadn't, see now @ChrisRackauckas

**Comment by ChrisRackauckas** [comment]
`DiffEqBayesLotkaVolterra.ipynb` is this supposed to be in there?

**Comment by Vaibhavdixit02** [comment]
Yeah, I added the plot_chain function for Turing to it.

**Pull request merged**
